config/routes.rb
Rails.application.routes.draw do
  root "categories#index"

  resources :categories
  resources :games do
    resources :reviews
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :games
  accepts_nested_attributes_for :games
  validates_presence_of :name
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :category
  accepts_nested_attributes_for :category
  has_many :reviews
  validates_presence_of :title
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :game
  accepts_nested_attributes_for :game
  validates_presence_of :comments, :game_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
      @categories = Category.all

      respond_to do |f|
        f.html
        f.json { render json: { categories: @categories } }
      end
  end

    def show
      @category = Category.find(params[:id])

      respond_to do |format|
        format.html
        format.json { render json: { category: @category, game: @games } }
      end
    end

  def create
    @category = Category.new(category_params)

    if @category.save
      render json: { category: @category, location: category_url(@category) }, status: :created
    else
      render json: { errors: @category.errors }, status: :unprocessable_entity
    end
  end

  def update
  @category = Category.find(params[:id])
  if @category.update(category_params)
    render json: { category: @category }, status: :accepted
  else
    render json: { errors: @category.errors }, status: :unprocessable_entity
  end
end

def destroy
  @category = Category.find(params[:id])
  if @category.destroy
    render json: { category: nil}, status: :accepted
  else
    render json: { errors: @category.errors}, status: :unprocessable_entity
  end
end

  protected

    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :set_game

  def index
    @games = Games.includes(:category).all

    respond_to do |format|
      format.html
      format.json { render json: { category: @category, games: @games } }
    end
  end

  def show

    respond_to do |format|
      format.html
      format.json { render json: { category: @category, game: @game } }
    end
  end

  def create
    @game = Game.new(game_params)
    @game.category = @category

    if @game.save
      redirect_to category_game_path(@category, @game), notice: "Game created successfully"
    else
      render :new
    end
  end

  protected

    def game_params
      params.require(:game).permit(:title, :id, :category)
    end

    def set_game
      @game = Game.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @game = Game.find(params[:id])
    @category = Category.find(params[:id])
    @reviews = Review.joins(game: :category).where(categories: {id: @category.id}, games: {id: @game.id})

    respond_to do |format|
      format.html
      format.json { render json: {category: @category, game: @game, reviews: @reviews} }
    end
  end

    def show
      @category = Category.find(:category_id)
      @game = Game.find(params[:id])
      @review = @game.review.find(params[:id])

      respond_to do |format|
        format.html
        format.json { render json: { game: @game, review: @review} }
      end
    end

    def create
      @review = Review.new(review_params)
      @review.game = @game

      if @review.save
        redirect_to game_review_path([@game, @review]), notice: "Thanks for your review"
      else
        render :new
      end
    end

    def update
      @review = Review.find(params[:id])

      if @review.update(review_params)
        render json: { review: @review}, status: :accepted
      else
        render json: { errors: @review.errors }, status: :unprocessable_entity
      end
    end

    def destroy
      @review = Review.find(params[:id])

      if @review.destroy
        render json: { review: nil}, status: :accepted
      else
        render json: { errors: @review.errors}, status: :unprocessable_entity
      end
    end

    protected
    def review_params
      params.require(:review).permit(:game_id, :comments)
    end

    def set_game
        @game = Game.find(params[:game_id])
        @review = @game.reviews.find(params[:id])

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/categories/index.html.erb
<h1>Videogame mania<h1>


<p> Welcome to videogames reviews!</p>

<h2>Pick your console</h2>

<% @categories.each do |category|  %>
  <h3><%= link_to category.name, category%></h3>
  <% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<p>Check out all the <strong><%= @category.name %></strong> games below!</p>

<% @category.games.each do |game|%>
<p><%= link_to game.title, game_path(game) %></p>
<% end %>

app/views/games/index.html.erb
<h1><%= @category.name %></h1>

<p>Check out all the <strong><%= @category.name %></strong> games below!</p>

<%= render @games %>

app/views/games/show.html.erb
<h1><%= @game.title %></h1>

<p>Read the reviews!</p>

<% @game.reviews.each do |review| %>
<%= review.comments %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Videogame Reviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/index.html.erb
<h1>Reviews!</h1>

<%= render @reviews %>

app/views/reviews/show.html.erb
<%= @reviews %>